# Generated by Django 5.1.15 on 2026-08-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="shopify_attribute_gid",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
