# Generated by Django 5.1.15 on 2026-08-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="correction_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
