# Generated by Django 5.1.15 on 2026-08-17 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classification", "0002_add_correction_notes"),
        ("products", "0004_add_processing_tracking_fields"),
        ("taxonomy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="classification",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_cls_status_created"
            ),
        ),
    ]
