# Generated by Django 5.1.15 on 2026-08-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classification", "0003_add_status_created_at_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="source",
            field=models.CharField(
                choices=[("AI", "AI"), ("Rule", "Rule")],
                db_index=True,
                default="AI",
                max_length=5,
            ),
        ),
    ]
