# Generated by Django 5.1.15 on 2026-08-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productimport"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
