# Generated by Django 5.1.15 on 2026-08-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_add_product_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
