# Generated by Django 5.1.15 on 2026-08-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_add_processing_tracking_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="retry_count",
        ),
    ]
