# Generated by Django 5.1.15 on 2026-08-19 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_retry_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_import",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.productimport",
            ),
        ),
    ]
